### ISSUE TITLE
Cannot find module '@ali/socket.io-client'

### ISSUE THREAD

**Issue by DThanhNg** [yorkie/node-naoqi#2]
When I run the code copying from "getting started" section, I got error:
Cannot find module '@ali/socket.io-client'

**Comment by yorkie** [comment]
Could you try with git clone?

**Comment by DThanhNg** [comment]
it doesn't work with git clone either. I can see that it includes package "socket.io-client": "1.0.2" in package.json, but in socket.js file import * as SocketIO from '@ali/socket.io-client';

**Comment by yorkie** [comment]
Could you please fix the following https://github.com/yorkie/node-naoqi/blob/master/src/socket.js#L4:

```js
import * as SocketIO from 'socket.io-client';
```

**Comment by GTMtremolo** [comment]
> Could you please fix the following https://github.com/yorkie/node-naoqi/blob/master/src/socket.js#L4:
> 
> ```js
> import * as SocketIO from 'socket.io-client';
> ```

how to fix it please

**Comment by yorkie** [comment]
Could you please try with official socket.io package, the old dependence "@ali/socket.io-client" had not maintained yet.
